image: registry.gitlab.com/yakshaving.art/go-builder:0.0.1
stages:
  - build
  - docker_image
  - release

# variables:
#   CGO_ENABLED: 0

cache:
  paths:
  - vendor

before_script:
  - mkdir -p /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - cd /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - ln -s ${CI_PROJECT_DIR}
  - cd /go/src/gitlab.com/${CI_PROJECT_PATH}

build:
  stage: build
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  artifacts:
    paths:
    - alertsnitch
  script:
  - dep ensure
  - make test
  - make build

build_arm:
  image: arm32v6/alpine:3.7
  stage: build
  artifacts:
    paths:
    - alertsnitch-arm
  script:
  - apk --no-cache add curl make go
  - go get github.com/golang/dep/cmd/dep
  - dep ensure
  - GOOS=linux GOARCH=arm GOARM=6 make build
  - mv alertsnitch alertsnitch-arm
  tags:
  - armv6

docker_image:
  stage: docker_image
  image:
    name: registry.yakshaving.art:443/tools/kaniko-shell:latest
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:latest
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.armv6 --destination $CI_REGISTRY_IMAGE:latest-armv6
  only:
  - master

release:
  stage: release
  image:
    name: registry.yakshaving.art:443/tools/kaniko-shell:latest
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
  - tags
