image: registry.gitlab.com/yakshaving.art/go-builder:0.0.1
stages:
  - test
  - build
  - release

variables:
  CGO_ENABLED: 0
  MYSQL_DATABASE: alertsnitch
  MYSQL_ROOT_PASSWORD: mysql
  ALERTSNITCHER_MYSQL_DSN: "root:${MYSQL_ROOT_PASSWORD}@/${MYSQL_DATABASE}"

cache:
  paths:
  - vendor

before_script:
  - mkdir -p /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - cd /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - ln -s ${CI_PROJECT_DIR}
  - cd /go/src/gitlab.com/${CI_PROJECT_PATH}

test:
  stage: test
  services:
  - mysql:5.7
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  script:
  - apk --no-cache add mysql-client
  - mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql \
    <( echo "CREATE DATABASE ${MYSQL_DATABASE};" )
  - mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql \
    "${MYSQL_DATABASE}" < db.d/0.0.1-bootstrap.sql
  - dep ensure
  - make integration

build:
  stage: build
  artifacts:
    paths:
    - alertsnitch
  script:
  - make build

docker_image:
  stage: release
  image:
    name: registry.yakshaving.art:443/tools/kaniko-shell:latest
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:latest
  only:
  - master

# release:
#   stage: release
#   image:
#     name: registry.yakshaving.art:443/tools/kaniko-shell:latest
#   script:
#     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
#     - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#   only:
#   - tags
