image: registry.gitlab.com/yakshaving.art/dockerfiles/go-builder:0.0.1
stages:
  - test
  - build
  - image
  - release

variables:
  MYSQL_DATABASE: alertsnitch
  MYSQL_ROOT_PASSWORD: mysql
  ALERTSNITCH_MYSQL_DSN: "root:${MYSQL_ROOT_PASSWORD}@tcp(mysql)/${MYSQL_DATABASE}"

cache:
  paths:
  - vendor

test:
  stage: test
  services:
  - mysql:5.7
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  script:
  - apk --no-cache add mysql-client
  - mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
  - mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}" < db.d/0.0.1-bootstrap.sql
  - go mod vendor
  - make integration

build:
  stage: build
  artifacts:
    paths:
    - alertsnitch-*
  variables:
    CGO_ENABLED: 0
  script:
  - make build
  - GOARCH=arm64 make build

.docker: &docker
  image: docker:stable
  services:
  - docker:dind
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  after_script:
    - docker logout

.build_image: &build_image
  <<: *docker
  stage: image
  script:
    - echo Building ${ARCH} image
    - cp Dockerfile.${ARCH} Dockerfile
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${ARCH}-latest .
    - docker push ${CI_REGISTRY_IMAGE}:${ARCH}-latest
    - rm Dockerfile

build_arm64:
  <<: *build_image
  variables:
    ARCH: arm64

build_amd64:
  <<: *build_image
  variables:
    ARCH: amd64

release_latest:
  <<: *docker
  stage: release
  script:
    - docker manifest create ${CI_REGISTRY_IMAGE}:latest ${CI_REGISTRY_IMAGE}:amd64-latest ${CI_REGISTRY_IMAGE}:arm64-latest
    - docker manifest annotate ${CI_REGISTRY_IMAGE} ${CI_REGISTRY_IMAGE}:arm64-latest --os linux --arch arm64
    - docker manifest push ${CI_REGISTRY_IMAGE}:latest
  # only:
  #   - master

release_tag:
  <<: *docker
  stage: release
  script:
    - docker manifest create ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} ${CI_REGISTRY_IMAGE}:amd64-latest ${CI_REGISTRY_IMAGE}:arm64-latest
    - docker manifest annotate ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} ${CI_REGISTRY_IMAGE}:arm64-latest --os linux --arch arm64
    - docker manifest push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
    - tags
