image: registry.gitlab.com/yakshaving.art/go-builder:0.0.1
stages:
  - prepare
  - build
  - docker_image
  - release

variables:
  CGO_ENABLED: 0
  MYSQL_DATABASE: alertsnitch
  MYSQL_ROOT_PASSWORD: mysql

cache:
  paths:
  - vendor

mysql_prepare:
  image: mysql
  stage: prepare
  services:
  - mysql
  script:
  - mysql -V
  - mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}" < db.d/01-bootstrap.sql

build:
  stage: build
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  artifacts:
    paths:
    - alertsnitch
  before_script:
  - mkdir -p /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - cd /go/src/gitlab.com/${CI_PROJECT_NAMESPACE}
  - ln -s ${CI_PROJECT_DIR}
  - cd /go/src/gitlab.com/${CI_PROJECT_PATH}
  - dep ensure
  script:
  - make test build

docker_image:
  stage: docker_image
  image:
    name: registry.yakshaving.art:443/tools/kaniko-shell:latest
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:latest
  only:
  - master

# release:
#   stage: release
#   image:
#     name: registry.yakshaving.art:443/tools/kaniko-shell:latest
#   script:
#     - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
#     - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.amd64 --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#   only:
#   - tags
