image: registry.gitlab.com/yakshaving.art/dockerfiles/go-builder:latest
stages:
  - build
  - image
  - release

variables:
  CGO_ENABLED: 0
  GOCACHE: ${CI_PROJECT_DIR}/.cache/go-build


test_mysql:
  stage: build
  cache:
    key: build-cache
    paths:
    - ${CI_PROJECT_DIR}/.cache/go-build
  services:
  - mysql:5.7
  variables:
    MYSQL_DATABASE: alertsnitch
    MYSQL_ROOT_PASSWORD: mysql
    ALERTSNITCH_MYSQL_DSN: "root:${MYSQL_ROOT_PASSWORD}@tcp(mysql)/${MYSQL_DATABASE}"
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  script:
  - apk --no-cache add mysql-client
  - mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
  - mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}" < db.d/mysql/0.0.1-bootstrap.sql
  - mysql --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}" < db.d/mysql/0.1.0-fingerprint.sql
  - go mod vendor
  - make integration

test_postgres:
  stage: build
  services:
  - postgres:11
  variables:
    POSTGRES_DB: alertsnitch
    POSTGRES_USER: alertsnitch
    POSTGRES_PASSWORD: mysql_har_har
    PG_HOST: postgres
    PG_USER: ${POSTGRES_USER}
    PG_PASSWORD: ${POSTGRES_PASSWORD}
    ALERTSNITCH_POSTGRES_DSN: "postgresql://${POSTGRES_USER}:@${PG_HOST}:5432/${POSTGRES_DB}?sslmode=disable"
  coverage: '/^total:\s+\(statements\)\s+(\d+.\d+)%$/'
  script:
  - apk --no-cache add postgres-client
  - psql -f db.d/postgres/0.0.1-bootstrap.sql ${POSTGRES_DB}
  - psql -f db.d/postgres/0.1.0-fingerprint.sql ${POSTGRES_DB}
  - go mod vendor
  - make integration

build:
  stage: build
  artifacts:
    paths:
    - alertsnitch-*
  script:
  - make build
  - GOARCH=arm64 make build
  - GOARCH=arm GOARM=6 make build

.docker: &docker
  image: docker:stable
  services:
  - docker:dind
  variables:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  after_script:
    - docker logout

.build_image: &build_image
  <<: *docker
  stage: image
  script:
    - echo Building ${ARCH} image
    - cp Dockerfile.${ARCH} Dockerfile
    - docker build --pull -t ${CI_REGISTRY_IMAGE}:${ARCH}-latest .
    - docker push ${CI_REGISTRY_IMAGE}:${ARCH}-latest
    - rm Dockerfile

build_arm64:
  <<: *build_image
  variables:
    ARCH: arm64

build_amd64:
  <<: *build_image
  variables:
    ARCH: amd64

build_armhf:
  <<: *build_image
  variables:
    ARCH: armhf

release_latest:
  <<: *docker
  stage: release
  script:
    - docker manifest create ${CI_REGISTRY_IMAGE}:latest
        ${CI_REGISTRY_IMAGE}:amd64-latest
        ${CI_REGISTRY_IMAGE}:arm64-latest
        ${CI_REGISTRY_IMAGE}:armhf-latest
    - docker manifest annotate ${CI_REGISTRY_IMAGE}
        ${CI_REGISTRY_IMAGE}:arm64-latest --os linux --arch arm64
    - docker manifest annotate ${CI_REGISTRY_IMAGE}
        ${CI_REGISTRY_IMAGE}:armhf-latest --os linux --arch arm --variant 6
    - docker manifest push ${CI_REGISTRY_IMAGE}:latest
  only:
    - master

release_tag:
  <<: *docker
  stage: release
  script:
    - docker manifest create ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
        ${CI_REGISTRY_IMAGE}:amd64-latest
        ${CI_REGISTRY_IMAGE}:arm64-latest
        ${CI_REGISTRY_IMAGE}:armhf-latest
    - docker manifest annotate ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
        ${CI_REGISTRY_IMAGE}:arm64-latest --os linux --arch arm64
    - docker manifest annotate ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
        ${CI_REGISTRY_IMAGE}:armhf-latest --os linux --arch arm --variant 6
    - docker manifest push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
    - tags
